#!/usr/bin/env python3
"""Write the release public key(s) into bootstrap.sh's emit_release_keys(), from PEMs CI derived.

WHY THIS EXISTS AT ALL: nobody should transcribe a public key into a file by hand. The private half lives
in a repository secret; the public half is DERIVED from it (`openssl ec -pubout`, deterministic) and put
here by machine. A key typed in by a person is a key that can be typed in wrongly, and the failure mode of
getting it wrong is not subtle — every install refuses every release, including the one that would fix it.

bootstrap.sh is the only place the key can live: the verifier cannot ship inside the tree it verifies, so
neither can the key that drives it. See docs/UPDATE-RESILIENCE-PLAN.md, Phase A.

Idempotent: the same secret derives the same PEM bytes, so a re-run rewrites the same content and the
signing workflow's commit step finds nothing to commit.

Usage: embed-release-keys.py <dir-holding-pub-N.pem> [bootstrap.sh]
"""
import glob
import os
import re
import sys

GENERATED = (
    "  # ⚠️ GENERATED by .github/workflows/sign-release.yml from the RELEASE_SIGNING_KEY secret(s).\n"
    "  # Do not edit by hand — the next signing run overwrites it, and a hand-typed key that is wrong\n"
    "  # makes every install refuse every release, including the one that would fix it.\n"
    "  #\n"
    "  # TWO keys once rotation is in play (RELEASE_SIGNING_KEY + RELEASE_SIGNING_KEY_NEXT): a release\n"
    "  # signed by either verifies, and that overlap is what stops a rotation stranding every box that\n"
    "  # has not updated yet — which are exactly the boxes hardest to reach.\n"
)


def main(argv):
    src_dir = argv[1] if len(argv) > 1 else "."
    boot = argv[2] if len(argv) > 2 else "bootstrap.sh"

    pems = sorted(glob.glob(os.path.join(src_dir, "pub-*.pem")))
    if not pems:
        sys.stderr.write("::error::no derived public keys in %s\n" % src_dir)
        return 1

    block = []
    for i, p in enumerate(pems, 1):
        pub = open(p, encoding="utf-8").read().strip()
        if "BEGIN PUBLIC KEY" not in pub:
            sys.stderr.write("::error::%s is not a PEM public key\n" % p)
            return 1
        # The heredoc is quoted and the PEM is flush-left on purpose: an unquoted heredoc would let the
        # shell expand the base64, and an indented one would keep the indentation inside the file, which
        # openssl will not parse.
        block.append('  cat > "$RELEASE_KEYS_D/release-%d.pub" <<\'PUBKEY\'\n%s\nPUBKEY\n' % (i, pub))

    src = open(boot, encoding="utf-8").read()
    # Replace only the BODY of the function — between its mkdir line and its closing brace — so the
    # function's name, its guard and everything around it stay exactly as shipped.
    m = re.search(r'(emit_release_keys\(\)\{\n  mkdir -p "\$RELEASE_KEYS_D"\n)(.*?)(\n\}\n)', src, re.S)
    if not m:
        sys.stderr.write("::error::could not find emit_release_keys() in %s — it has drifted\n" % boot)
        return 1

    out = src[:m.end(1)] + GENERATED + "".join(block) + m.group(3) + src[m.end(3):]
    if out == src:
        print("release keys already current — nothing to change")
        return 0
    open(boot, "w", encoding="utf-8").write(out)
    print("embedded %d release key(s) into %s" % (len(pems), boot))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
