#!/usr/bin/env python3
"""Self-test: what a docker RE-INSTALL says about the login, the image pin and itself is true.

Three findings of the 1.8.8-beta VM upgrade re-run:
  · LOGIN. uninstall.sh keeps data/ + .env for a later re-install but strips PANEL_PASSWORD from the .env (no
    plaintext password at rest). The re-install then minted a random password, deleted the kept login
    (data/etc/auth) and printed "new login — save the password now": the operator's own password stopped working
    and nothing said why. The kept login is the right answer (bare-metal's install-host keeps it too); a placeholder
    in .env ("(preserved)", which a convert writes) must never become the password either.
  · IMAGE PIN. The re-install kept SWG_IMAGE_TAG but its "kept from the previous .env:" line did not say so.
  · LABEL. Every plain re-install reported "re-installed and updated" to the panel, a same-image one included.

  [1] no password known (stripped by an uninstall, or a placeholder) + a kept login → the login is kept, and said
  [2] …a password given this run (-pass), or a real one in .env, is still applied as before
  [3] a kept login's user name is kept even when it is "admin" (no admin### rename over a kept login)
  [4] the "kept from the previous .env:" line names SWG_IMAGE_TAG when the pin is kept
  [5] the lifecycle label: "reinstalled-updated" only when a running container's image changed

[1]–[4] are real `install-docker.sh --dry-run` runs against a stored install dir; [5] runs the shipped post-`up`
block with `docker inspect` stubbed.

Run: python3 tests/docker_reinstall_login_label_selftest.py      (0 = pass)
     --perturb   re-plants the shipped behaviour (mint over a kept login, tag unmentioned, always "updated") → RED
"""
import os, re, shutil, subprocess, sys, tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PERTURB = "--perturb" in sys.argv
FAILS = []


def check(name, cond, detail=""):
    print(("  PASS " if cond else "  FAIL ") + name + (("  — %s" % (detail,)) if detail and not cond else ""))
    if not cond:
        FAILS.append(name)


T = tempfile.mkdtemp(prefix="dockerlogin-")
SRC = os.path.join(T, "src")
shutil.copytree(ROOT, SRC, ignore=shutil.ignore_patterns(".git", "dryrun", "node_modules", "*.png", "scratchpad", "docs",
                                                         ".campaign", "__pycache__", "forks", "screenshots", ".claude"))
INST_SH = os.path.join(SRC, "install-docker.sh")
inst = open(INST_SH, encoding="utf-8").read()
if PERTURB:
    m = re.search(r"\n# ⚠️ …AND A RE-INSTALL THAT DOESN'T KNOW THE PASSWORD KEEPS THE LOGIN IT HAS\..*?\nfi\n", inst, re.S)
    assert m, "perturbation anchor missing (login keep) — this run would FALSE-PASS"
    inst = inst[:m.start()] + "\nKEPT_LOGIN=no\n" + inst[m.end():]
    for a, b in [('"SWG_IMAGE_TAG=$(_env_val SWG_IMAGE_TAG "$INSTALL_DIR/.env")"; _KEPT_TAG=yes;;', '"SWG_IMAGE_TAG=$(_env_val SWG_IMAGE_TAG "$INSTALL_DIR/.env")";;'),
                 ('    LC_SUCCESS=reinstalled\n', '    :\n')]:
        assert inst.count(a) == 1, "perturbation anchor missing — this run would FALSE-PASS: %r" % a[:60]
        inst = inst.replace(a, b, 1)
    open(INST_SH, "w", encoding="utf-8").write(inst)

BASE = """# generated by install-docker.sh — profile: master
PANEL_USER=%s
PANEL_DOMAIN=192.168.77.3
TLS=selfsigned
PANEL_PORT=2087
PANEL_URL=http://127.0.0.1:8088
NODE_TOKEN=stored-token-0123456789
NODE_ENDPOINT=192.168.77.3
NODE_NET=host
TURN_MANAGE=panel
TLS_VERIFY=no
SWG_IMAGE_TAG=sha-c5cb1df
"""


def dry(label, user="admin301", pw_line="", auth_user="admin301", args=(), env_extra=None):
    d = os.path.join(T, "inst-" + label); os.makedirs(os.path.join(d, "data", "etc"))
    open(os.path.join(d, ".env"), "w").write((BASE % user) + pw_line)
    if auth_user:
        open(os.path.join(d, "data", "etc", "auth"), "w").write(auth_user + ":pbkdf2_sha256$200000$c2FsdA==$aGFzaA==\n")
    env = dict(os.environ, SWG_DOCKER_DIR=d)
    for k in ("TLS", "PANEL_PASSWORD", "PANEL_USER", "SWG_IMAGE_TAG"):
        env.pop(k, None)
    env.update(env_extra or {})
    r = subprocess.run(["bash", "install-docker.sh", "host", "-role", "master", *args, "--dry-run"], cwd=SRC, env=env,
                       stdin=subprocess.DEVNULL, capture_output=True, text=True, timeout=300, start_new_session=True)
    rendered = os.path.join(SRC, "dryrun" + d, ".env")
    txt = open(rendered).read() if os.path.exists(rendered) else ""
    val = lambda k: (re.search(r"^%s=(.*)$" % k, txt, re.M) or [None, None])[1]
    return r.returncode, r.stdout + r.stderr, val


print("[1] no password known + a kept login → the login is kept")
rc, out, val = dry("stripped")                                     # what uninstall.sh leaves: no PANEL_PASSWORD line
check("the dry run completed", rc == 0 and "DRY RUN done" in out, (rc, out[-400:]))
check("⚠️ it says it keeps the existing login", "Keeping the existing panel login" in out and "admin301" in out, out[-900:])
check("…no password is minted into .env (a placeholder, never a live password)", val("PANEL_PASSWORD") == "(preserved)", val("PANEL_PASSWORD"))
check("…the user name is the kept login's", val("PANEL_USER") == "admin301", val("PANEL_USER"))
rc, out, val = dry("placeholder", pw_line="PANEL_PASSWORD=(preserved)\n")
check("a placeholder in .env is not a password: the login is kept", "Keeping the existing panel login" in out and val("PANEL_PASSWORD") == "(preserved)", val("PANEL_PASSWORD"))

print("\n[2] a real password still wins")
rc, out, val = dry("given", args=("-pass", "GivenPass123"))
check("-pass given: applied, no keep", "Keeping the existing panel login" not in out and val("PANEL_PASSWORD") == "GivenPass123", val("PANEL_PASSWORD"))
rc, out, val = dry("envpw", pw_line="PANEL_PASSWORD=StoredPass123\n")
check("a real password in .env: re-applied as before, no keep", "Keeping the existing panel login" not in out and val("PANEL_PASSWORD") == "StoredPass123", val("PANEL_PASSWORD"))
rc, out, val = dry("noauth", auth_user=None)
check("no kept login at all: a password is minted as before", "Keeping the existing panel login" not in out and val("PANEL_PASSWORD") not in (None, "", "(preserved)"), val("PANEL_PASSWORD"))

print("\n[3] a kept login named 'admin' is not renamed")
rc, out, val = dry("admin", user="admin", auth_user="admin")
check("PANEL_USER stays admin", val("PANEL_USER") == "admin", val("PANEL_USER"))

print("\n[4] the kept-keys line names the image pin")
rc, out, val = dry("tag", pw_line="SWG_LATEST_URL=https://example/dev/VERSION\n")
line = next((l for l in out.splitlines() if "kept from the previous .env:" in l), "")
check("⚠️ SWG_IMAGE_TAG is named", "SWG_IMAGE_TAG" in line, line)
check("…with the carried keys", "SWG_LATEST_URL" in line, line)
check("and the pin really is kept", val("SWG_IMAGE_TAG") == "sha-c5cb1df", val("SWG_IMAGE_TAG"))

print("\n[5] the lifecycle label")
blk = re.search(r'\n(if \[ "\$\{LC_SUCCESS:-\}" = reinstalled-updated \] && ! \$DRYRUN; then\n.*?\nfi\n)', inst, re.S)
check("the post-up label block exists", blk is not None)
STUB = os.path.join(T, "stub"); os.makedirs(STUB)


def label(before, after):
    open(os.path.join(STUB, "docker"), "w").write("#!/bin/sh\ncat <<'X'\n%s\nX\n" % after)
    os.chmod(os.path.join(STUB, "docker"), 0o755)
    s = 'set -euo pipefail\nDRYRUN=false; LC_SUCCESS=reinstalled-updated; _IMG_BEFORE="$1"\n%s\necho "LABEL=$LC_SUCCESS"\n' % (blk.group(1) if blk else "")
    r = subprocess.run(["bash", "-c", s, "x", before], env=dict(os.environ, PATH=STUB + os.pathsep + os.environ["PATH"]),
                       capture_output=True, text=True)
    m = re.search(r"LABEL=(\S+)", r.stdout)
    return m.group(1) if m else r.stdout + r.stderr


SAME = "/swg-node sha256:aaa\n/swg-panel sha256:bbb"
check("⚠️ same images → re-installed (not 'updated')", label(SAME, SAME) == "reinstalled", label(SAME, SAME))
check("a changed image → re-installed and updated", label(SAME, "/swg-node sha256:aaa\n/swg-panel sha256:ccc") == "reinstalled-updated")
check("nothing was running (an uninstall came first) → re-installed", label("", SAME) == "reinstalled", label("", SAME))

shutil.rmtree(T, ignore_errors=True)
print("\n%s — %d failed" % ("RED" if FAILS else "GREEN", len(FAILS)))
if PERTURB:
    print("(--perturb expects RED above)")
sys.exit(1 if FAILS else 0)
