#!/usr/bin/env python3
"""Self-test: a docker NODE re-install keeps (or re-takes) its panel-certificate pin — it never silently drops to
"verify nothing".

Measured in the 1.8.8-beta qualification (guest q4, a docker node enrolled to a self-signed panel): the .env had
TLS_FINGERPRINT=<sha256>; after a re-install it had `TLS_FINGERPRINT=` and `TLS_VERIFY=no`, and swg-noded's config
said `verify: False` with no fingerprint — the node synced trusting any certificate at all. The re-install branch of
ask_node_conn asked a bare "Verify? (y/N)" defaulted from the stored TLS_VERIFY — `no` on every pinned node, since a
pin is how a self-signed panel is trusted — and never read TLS_FINGERPRINT (the .env import did not even load it).
A fresh install of the same node pins ("Panel cert is self-signed — pinning it").

  [1] re-install, same panel URL: the stored pin is carried into the new .env (dry run: not re-probed)
  [2] re-install to a DIFFERENT panel URL: the old pin is not carried — and the result is never "no + no pin"
  [3] node_panel_trust itself, against a live self-signed TLS listener (the real probe, DRYRUN=false):
      a. stored pin == the certificate served      → kept, and it says so
      b. stored pin != the certificate served      → NEVER taken silently (1.8.8 round 4): with no terminal the old pin
         is kept, with a CHANGED warning and the way to accept it (TLS_FINGERPRINT=<served>); at a terminal the
         operator is asked — y re-pins to the served one, Enter (the default) keeps the old pin
      c. stored pin, panel unreachable             → kept (a panel outage must not cost the node its pin)
      d. no stored pin, self-signed panel          → pinned (the fresh-install behaviour, unchanged)
      e. the stored pin written `AB:CD:…`          → the same certificate: kept (swg-noded compares it that way)

Run: python3 tests/docker_reinstall_keeps_pin_selftest.py      (0 = pass)
     --perturb   re-plants the shipped re-install branch (bare verify prompt from the stored TLS_VERIFY) and a
                 node_panel_trust that ignores the stored pin → RED
"""
import hashlib, http.server, os, re, shutil, socket, ssl, subprocess, sys, tempfile, threading

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PERTURB = "--perturb" in sys.argv
FAILS = []


def check(name, cond, detail=""):
    print(("  PASS " if cond else "  FAIL ") + name + (("  — %s" % (detail,)) if detail and not cond else ""))
    if not cond:
        FAILS.append(name)


T = tempfile.mkdtemp(prefix="dockerpin-")
SRC = os.path.join(T, "src")
shutil.copytree(ROOT, SRC, ignore=shutil.ignore_patterns(".git", "dryrun", "node_modules", "*.png", "scratchpad", "docs",
                                                         ".campaign", "__pycache__", "forks", "screenshots", ".claude"))
INST_SH = os.path.join(SRC, "install-docker.sh")
inst = open(INST_SH, encoding="utf-8").read()
if PERTURB:
    m = re.search(r'\n    if \[ -n "\$\{_GIVEN_TLS_VERIFY:-\}" \].*?\n    fi\n', inst, re.S)
    assert m, "perturbation anchor missing — this run would FALSE-PASS"
    inst = inst[:m.start()] + '\n    TLS_VERIFY="$(ask_yn_tty "Verify the panel\'s TLS certificate? (answer no if the panel uses a self-signed cert)" ' \
        '"$([ "$_extls" = yes ] && echo y || echo n)")"\n' + inst[m.end():]
    a = '''    if [ -z "$_fp" ] || [ "$_fp" = "$(printf '%s' "$_old" | tr -d ':' | tr 'A-F' 'a-f')" ]; then'''
    assert inst.count(a) == 1, "perturbation anchor missing — this run would FALSE-PASS"
    inst = inst.replace(a, "    if false; then", 1)
    open(INST_SH, "w", encoding="utf-8").write(inst)

PIN = "ab" * 32


def closed_port():
    s = socket.socket(); s.bind(("127.0.0.1", 0)); p = s.getsockname()[1]; s.close(); return p


def dry(label, stored, args):
    inst_dir = os.path.join(T, "inst-" + label); os.makedirs(inst_dir)
    open(os.path.join(inst_dir, ".env"), "w").write(stored)
    env = dict(os.environ, SWG_DOCKER_DIR=inst_dir)
    for k in ("TLS_VERIFY", "TLS_FINGERPRINT", "PANEL_URL", "NODE_TOKEN"):
        env.pop(k, None)
    r = subprocess.run(["bash", "install-docker.sh", *args, "--dry-run"], cwd=SRC, env=env, stdin=subprocess.DEVNULL,
                       capture_output=True, text=True, timeout=300, start_new_session=True)
    rendered = os.path.join(SRC, "dryrun" + inst_dir, ".env")
    vals = {}
    for ln in (open(rendered).read() if os.path.exists(rendered) else "").splitlines():
        mm = re.match(r"^([A-Za-z_][A-Za-z0-9_]*)=(.*)$", ln)
        if mm and mm.group(1) not in vals:
            vals[mm.group(1)] = re.sub(r"\s+#.*$", "", mm.group(2)).strip()
    return r.returncode, r.stdout + r.stderr, vals


URL = "https://127.0.0.1:%d" % closed_port()
STORED = """# generated by install-docker.sh — profile: node
PANEL_PASSWORD=unused-on-node-only
PANEL_DOMAIN=localhost
PANEL_URL=%s
NODE_TOKEN=stored-token-0123456789
NODE_ENDPOINT=192.168.77.4
NODE_NET=host
TURN_MANAGE=panel
TLS_VERIFY=no
TLS_FINGERPRINT=%s
""" % (URL, PIN)

print("[1] re-install, same panel URL: the stored pin is carried")
rc, out, v = dry("same", STORED, ["node"])
check("the dry run completed", rc == 0 and "DRY RUN done" in out, (rc, out[-400:]))
check("⚠️ TLS_FINGERPRINT is the stored pin", v.get("TLS_FINGERPRINT") == PIN, v.get("TLS_FINGERPRINT"))
check("TLS_VERIFY=no (the pin is the verification)", v.get("TLS_VERIFY") == "no", v.get("TLS_VERIFY"))

print("\n[2] re-install to a different panel URL: the old pin stays behind, and nothing downgrades to 'trust anything'")
rc, out, v = dry("moved", STORED, ["node", "-host", "https://127.0.0.1:%d" % closed_port()])
check("the dry run completed", rc == 0 and "DRY RUN done" in out, (rc, out[-400:]))
check("the old URL's pin is not carried to a new URL", v.get("TLS_FINGERPRINT") != PIN, v.get("TLS_FINGERPRINT"))
check("⚠️ never TLS_VERIFY=no with no pin", not (v.get("TLS_VERIFY") == "no" and not v.get("TLS_FINGERPRINT")),
      (v.get("TLS_VERIFY"), v.get("TLS_FINGERPRINT")))

# ── [3] the function, with the real probe against a real listener ─────────────────────────────────────────────
CERT, KEY = os.path.join(T, "c.pem"), os.path.join(T, "k.pem")
subprocess.run(["openssl", "req", "-x509", "-newkey", "rsa:2048", "-nodes", "-days", "30", "-subj", "/CN=127.0.0.1",
                "-addext", "subjectAltName=IP:127.0.0.1", "-keyout", KEY, "-out", CERT], check=True, capture_output=True)
SERVED = hashlib.sha256(ssl.PEM_cert_to_DER_cert(open(CERT).read())).hexdigest()


class H(http.server.BaseHTTPRequestHandler):
    def do_GET(self):
        self.send_response(200); self.end_headers(); self.wfile.write(b"ok")

    def log_message(self, *a):
        pass


srv = http.server.ThreadingHTTPServer(("127.0.0.1", 0), H)
ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER); ctx.load_cert_chain(CERT, KEY)
srv.socket = ctx.wrap_socket(srv.socket, server_side=True)
threading.Thread(target=srv.serve_forever, daemon=True).start()
LIVE = "https://127.0.0.1:%d" % srv.server_address[1]
DEAD = "https://127.0.0.1:%d" % closed_port()


def extract(src, name):
    """The definition of shell function `name` exactly as shipped: from its `name(){` line to the first line at which
    the text so far is a complete, parseable definition."""
    lines = src.splitlines()
    start = next(i for i, l in enumerate(lines) if l.startswith(name + "(){"))
    for end in range(start, len(lines)):
        chunk = "\n".join(lines[start:end + 1])
        if chunk.rstrip().endswith("}") and subprocess.run(["bash", "-n"], input=chunk, text=True, capture_output=True).returncode == 0:
            return chunk
    raise AssertionError("could not extract " + name)


FUNCS = "\n".join(extract(inst, n) for n in ("info", "_docker_panel_fp", "sub", "ok", "warn", "b",
                                             "ask_tty", "ask_yn_tty", "node_panel_trust"))


def trust(url, old, answer=None):
    """answer=None: no terminal (a new session, stdin closed). A string: run on a pty and type it."""
    script = ('set -euo pipefail\nDRYRUN=false; HAVE_TTY=no; _SWG_NL=""; BOLD=""; RESET=""; C_BLUE=""; C_GREEN=""; C_BL=""; C_BROWN=""\n'
              '_nlguard(){ _SWG_NL=""; }\n'
              '. "%s/lib/common.sh"\n%s\nPANEL_URL="%s"; TLS_VERIFY=""; TLS_FINGERPRINT=""\n'
              'node_panel_trust "%s"\necho "RESULT verify=$TLS_VERIFY fp=$TLS_FINGERPRINT"\n') % (SRC, FUNCS, url, old)
    if answer is None:
        r = subprocess.run(["bash", "-c", script], stdin=subprocess.DEVNULL, capture_output=True, text=True, timeout=120,
                           start_new_session=True)
    else:
        f = os.path.join(T, "trust.sh"); open(f, "w").write(script)
        r = subprocess.run(["script", "-qec", "bash " + f, "/dev/null"], input=answer, capture_output=True, text=True,
                           timeout=120, start_new_session=True)
    out = r.stdout + r.stderr
    m = re.search(r"RESULT verify=(\S*) fp=(\S*)", out)
    return (m.group(1), m.group(2)) if m else (None, None), out


print("\n[3] node_panel_trust against a live self-signed listener")
(vf, fp), out = trust(LIVE, SERVED)
check("a. stored pin == served → kept", (vf, fp) == ("no", SERVED), (vf, fp, out[-300:]))
check("a. …and it says the panel still presents it", "still presents" in out, out[-300:])
(vf, fp), out = trust(LIVE, PIN)
check("b. stored pin != served, no terminal → the OLD pin is kept (a changed certificate is never accepted unattended)",
      (vf, fp) == ("no", PIN), (vf, fp, out[-300:]))
check("b. …with a CHANGED warning, and the way to accept the new one", "CHANGED" in out and ("TLS_FINGERPRINT=" + SERVED) in out, out[-400:])
(vf, fp), out = trust(LIVE, PIN, "y\n")
check("b. …at a terminal, y → re-pinned to the served certificate", (vf, fp) == ("no", SERVED), (vf, fp, out[-300:]))
(vf, fp), out = trust(LIVE, PIN, "\n")
check("b. …at a terminal, Enter (the default) → the old pin is kept", (vf, fp) == ("no", PIN), (vf, fp, out[-300:]))
(vf, fp), out = trust(DEAD, PIN)
check("c. ⚠️ panel unreachable → the stored pin is kept", (vf, fp) == ("no", PIN), (vf, fp, out[-300:]))
(vf, fp), out = trust(LIVE, "")
check("d. no stored pin, self-signed → pinned", (vf, fp) == ("no", SERVED), (vf, fp, out[-300:]))
COLON = ":".join(SERVED[i:i + 2] for i in range(0, 64, 2)).upper()   # the `AB:CD:…` form a hand edit / bare config may carry
(vf, fp), out = trust(LIVE, COLON)
check("e. the same pin written AB:CD:… is the same certificate — kept, not CHANGED",
      (vf, fp) == ("no", COLON) and "CHANGED" not in out, (vf, fp, out[-300:]))

srv.shutdown()
shutil.rmtree(T, ignore_errors=True)
print("\n%s — %d failed" % ("RED" if FAILS else "GREEN", len(FAILS)))
if PERTURB:
    print("(--perturb expects RED above)")
sys.exit(1 if FAILS else 0)
