#!/usr/bin/env python3
"""Self-test: a docker PANEL re-install given TLS=selfsigned keeps a self-signed certificate that already fits —
so the nodes pinned to it keep syncing.

Measured in the 1.8.8-beta qualification: re-installing the docker master q3 with TLS=selfsigned re-issued its
self-signed certificate every time (the installer deletes data/etc/tls/*.pem on a re-install, and the entrypoint
generates a new one), and its docker node q4 — pinned to the old certificate, as every node of a self-signed panel is —
went dark with "sync error: tls fingerprint mismatch" until it was re-installed too. Nothing was gained: the old
certificate already named the host.

Decision (coordinator, 2026-09-26): stability first. Keep the cert when ALL of these hold, otherwise behave as before:
the TLS mode was GIVEN (not picked from a menu that offered reuse) and is selfsigned; it is a re-install; the cert on
disk is self-signed (issuer == subject), has its key, and covers the panel host.

  [1] given selfsigned + a fitting self-signed cert → "keeping the existing self-signed certificate"
  [2] …not when the cert names another host
  [3] …not when the cert is CA-issued (issuer != subject), even though it covers the host
  [4] …not when the key is missing (keeping half a pair would leave the panel unable to serve TLS)
  [5] …not for another given mode (none), and not without a cert
  [6] …not when selfsigned is NOT given: the menu path still offers reuse / lets the operator ask for a new one
  [7] the re-install reset, run as shipped: KEEP_CERT spares both cert files (the login is still re-applied);
      without it both are removed, as before — and the convert (KEEP_AUTH) branch honours it too

[1]–[6] are real `install-docker.sh --dry-run` runs (the decision reads the live cert, read-only); [7] lifts the
reset block out of install-docker.sh verbatim and runs it for real against a temp install dir.

Run: python3 tests/docker_reinstall_keeps_selfsigned_selftest.py      (0 = pass)
     --perturb   re-plants the shipped behaviour (no keep decision; the reset always removes the cert) → RED
"""
import os, re, shutil, subprocess, sys, tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PERTURB = "--perturb" in sys.argv
FAILS = []


def check(name, cond, detail=""):
    print(("  PASS " if cond else "  FAIL ") + name + (("  — %s" % (detail,)) if detail and not cond else ""))
    if not cond:
        FAILS.append(name)


T = tempfile.mkdtemp(prefix="dockerkeepss-")
SRC = os.path.join(T, "src")
shutil.copytree(ROOT, SRC, ignore=shutil.ignore_patterns(".git", "dryrun", "node_modules", "*.png", "scratchpad", "docs",
                                                         ".campaign", "__pycache__", "forks", "screenshots", ".claude"))
INST_SH = os.path.join(SRC, "install-docker.sh")
inst = open(INST_SH, encoding="utf-8").read()
if PERTURB:
    m = re.search(r"\n  case \"\$_tls_in\" in s\|self\|selfsigned\)\n.*?\n  esac\n", inst, re.S)
    assert m, "perturbation anchor missing (keep decision) — this run would FALSE-PASS"
    inst = inst[:m.start()] + "\n" + inst[m.end():]
    guard = '[ "${KEEP_CERT:-no}" = yes ] || '
    assert inst.count(guard) == 2, "perturbation anchor missing (reset guards) — this run would FALSE-PASS"
    inst = inst.replace(guard, "")
    open(INST_SH, "w", encoding="utf-8").write(inst)

STORED = """# generated by install-docker.sh — profile: master
PANEL_PASSWORD=storedpass123
PANEL_USER=admin899
PANEL_DOMAIN=192.168.77.3
TLS=selfsigned
PANEL_PORT=2087
PANEL_URL=http://127.0.0.1:8088
NODE_TOKEN=stored-token-0123456789
NODE_ENDPOINT=192.168.77.3
NODE_NET=host
TURN_MANAGE=panel
TLS_VERIFY=no
"""
HOST = "192.168.77.3"


def ossl(*a):
    subprocess.run(["openssl", *a], check=True, capture_output=True)


def make_cert(tls, host, ca_signed=False, key=True):
    os.makedirs(tls, exist_ok=True)
    k, c = os.path.join(tls, "key.pem"), os.path.join(tls, "fullchain.pem")
    if not ca_signed:
        ossl("req", "-x509", "-newkey", "rsa:2048", "-nodes", "-days", "30", "-subj", "/CN=%s" % host,
             "-addext", "subjectAltName=IP:%s" % host, "-keyout", k, "-out", c)
    else:
        cak, cac, csr, ext = (os.path.join(T, x) for x in ("ca.key", "ca.pem", "leaf.csr", "leaf.ext"))
        if not os.path.exists(cac):
            ossl("req", "-x509", "-newkey", "rsa:2048", "-nodes", "-days", "30", "-subj", "/CN=Test CA", "-keyout", cak, "-out", cac)
        ossl("req", "-newkey", "rsa:2048", "-nodes", "-subj", "/CN=%s" % host, "-keyout", k, "-out", csr)
        open(ext, "w").write("subjectAltName=IP:%s\n" % host)
        ossl("x509", "-req", "-in", csr, "-CA", cac, "-CAkey", cak, "-CAcreateserial", "-days", "30", "-extfile", ext, "-out", c)
    if not key:
        os.remove(k)


def dry(label, cert=None, env_extra=None):
    inst_dir = os.path.join(T, "inst-" + label); os.makedirs(inst_dir)
    open(os.path.join(inst_dir, ".env"), "w").write(STORED)
    if cert:
        make_cert(os.path.join(inst_dir, "data", "etc", "tls"), **cert)
    env = dict(os.environ, SWG_DOCKER_DIR=inst_dir)
    for k in ("TLS", "PANEL_DOMAIN", "SWG_IMAGE_TAG"):
        env.pop(k, None)
    env.update(env_extra or {})
    r = subprocess.run(["bash", "install-docker.sh", "host", "-role", "master", "--dry-run"], cwd=SRC, env=env,
                       stdin=subprocess.DEVNULL, capture_output=True, text=True, timeout=300, start_new_session=True)
    return r.returncode, r.stdout + r.stderr


KEEP = "keeping the existing self-signed certificate"

print("[1] given selfsigned + a fitting self-signed cert → kept")
rc, out = dry("fits", cert={"host": HOST}, env_extra={"TLS": "selfsigned"})
check("the dry run completed", rc == 0 and "DRY RUN done" in out, (rc, out[-400:]))
check("⚠️ it keeps the certificate, and says why", KEEP in out and "pinned to it keep syncing" in out, out[-900:])
rc, out = dry("fits-alias", cert={"host": HOST}, env_extra={"TLS": "s"})
check("…the short alias `s` counts as given selfsigned too", KEEP in out, out[-600:])

print("\n[2] a cert for another host → not kept")
rc, out = dry("otherhost", cert={"host": "10.0.2.15"}, env_extra={"TLS": "selfsigned"})
check("re-issued (no keep line)", rc == 0 and KEEP not in out, out[-600:])

print("\n[3] a CA-issued cert that covers the host → not kept")
rc, out = dry("casigned", cert={"host": HOST, "ca_signed": True}, env_extra={"TLS": "selfsigned"})
check("re-issued (no keep line)", rc == 0 and KEEP not in out, out[-600:])

print("\n[4] the key is missing → not kept")
rc, out = dry("nokey", cert={"host": HOST, "key": False}, env_extra={"TLS": "selfsigned"})
check("re-issued (no keep line)", rc == 0 and KEEP not in out, out[-600:])

print("\n[5] another given mode, or no cert → not kept")
rc, out = dry("none", cert={"host": HOST}, env_extra={"TLS": "none"})
check("TLS=none: no keep line", rc == 0 and KEEP not in out, out[-600:])
rc, out = dry("nocert", env_extra={"TLS": "selfsigned"})
check("no cert on disk: no keep line", rc == 0 and KEEP not in out, out[-600:])

print("\n[6] selfsigned NOT given → the menu path, unchanged")
rc, out = dry("menu", cert={"host": HOST})
check("reuse is offered as the default (and taken with no terminal)", "euse (default)" in out and "reusing the existing certificate" in out, out[-900:])
check("…and the keep line is not what decided it", KEEP not in out)

print("\n[7] the re-install reset honours KEEP_CERT")
m = re.search(r'\nif \[ "\$PROFILE" != node \]; then\n  if \[ "\$\{REUSE_TLS:-no\}" = yes \]; then\n.*?\n  fi\nfi\n', inst, re.S)
assert m, "reset block missing — this run would FALSE-PASS"
RESET = m.group(0)


def reset(keep_cert, keep_auth="no"):
    d = tempfile.mkdtemp(dir=T)
    tls = os.path.join(d, "data", "etc", "tls"); os.makedirs(tls)
    for f in (os.path.join(d, "data", "etc", "auth"), os.path.join(tls, "fullchain.pem"), os.path.join(tls, "key.pem")):
        open(f, "w").write("x")
    script = ('set -euo pipefail\nDRYRUN=false; PREFIX=""; PROFILE=master; INSTALL_DIR="%s"; REUSE_TLS=no; KEEP_AUTH=%s; '
              'KEEP_CERT=%s; NEW_LOGIN=no\n%s\necho "NEW_LOGIN=$NEW_LOGIN"\n') % (d, keep_auth, keep_cert, RESET)
    r = subprocess.run(["bash", "-c", script], capture_output=True, text=True, timeout=30)
    ex = lambda *p: os.path.exists(os.path.join(d, "data", "etc", *p))
    return r.returncode, ex("auth"), ex("tls", "fullchain.pem"), ex("tls", "key.pem"), "NEW_LOGIN=yes" in r.stdout


rc, auth, cert, key, newlogin = reset("yes")
check("⚠️ KEEP_CERT=yes: fullchain.pem and key.pem are NOT removed", rc == 0 and cert and key, (rc, cert, key))
check("…the login is still re-applied (auth removed, NEW_LOGIN=yes), as before", not auth and newlogin, (auth, newlogin))
rc, auth, cert, key, newlogin = reset("no")
check("KEEP_CERT=no: the cert files are removed, as before", rc == 0 and not cert and not key, (rc, cert, key))
rc, auth, cert, key, newlogin = reset("yes", keep_auth="yes")
check("convert (KEEP_AUTH): the kept cert and the staged login both survive", rc == 0 and cert and key and auth, (rc, cert, key, auth))

shutil.rmtree(T, ignore_errors=True)
print("\n%s — %d failed" % ("RED" if FAILS else "GREEN", len(FAILS)))
if PERTURB:
    print("(--perturb expects RED above)")
sys.exit(1 if FAILS else 0)
