#!/usr/bin/env python3
"""Self-test: install-docker.sh with NO terminal (setsid … </dev/null, cron, CI) takes its defaults without raw shell
errors, and a --dry-run tells the truth about what it did.

Measured in the 1.8.8-beta qualification (unattended runs on guests q3/q4):
  · `install-docker.sh: line 216: /dev/tty: No such device or address` (and line 204) at every prompt — a failed
    `read … </dev/tty` redirection, which no trailing 2>/dev/null can cover;
  · the unattended "Step 5. Networking mode" menu followed by that same raw error;
  · "Press Enter to keep each value" printed to a log that has no terminal behind it;
  · a --dry-run banner saying "no Docker commands run", and a dry-run summary announcing "RE-INSTALL COMPLETE" and
    "Panel (new login — save the password now…)" with a password that was never applied (print_summary describes
    the LIVE box: it reads the installed .env and `docker exec`s the running containers).

  [1] fresh master, no terminal (the Networking-mode menu is reached): no /dev/tty error, each default is named
  [2] node re-install, no terminal: no "Press Enter", no /dev/tty error
  [3] dry-run output: no "COMPLETE", no "new login"/"save the password", no "no Docker commands run" — and it says
      nothing was installed

Run: python3 tests/docker_unattended_quiet_selftest.py      (0 = pass)
     --perturb   forces the old tty handling (every prompt reads /dev/tty) and the old dry-run summary → RED
"""
import os, re, shutil, subprocess, sys, tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PERTURB = "--perturb" in sys.argv
FAILS = []


def check(name, cond, detail=""):
    print(("  PASS " if cond else "  FAIL ") + name + (("  — %s" % (detail,)) if detail and not cond else ""))
    if not cond:
        FAILS.append(name)


T = tempfile.mkdtemp(prefix="dockerquiet-")
SRC = os.path.join(T, "src")
shutil.copytree(ROOT, SRC, ignore=shutil.ignore_patterns(".git", "dryrun", "node_modules", "*.png", "scratchpad", "docs",
                                                         ".campaign", "__pycache__", "forks", "screenshots", ".claude"))
INST_SH = os.path.join(SRC, "install-docker.sh")
inst = open(INST_SH, encoding="utf-8").read()
if PERTURB:
    for a, b in [
        ("HAVE_TTY=no; { : </dev/tty; } 2>/dev/null && HAVE_TTY=yes", "HAVE_TTY=yes"),   # every prompt tries the tty
        ("elif $DRYRUN; then\n  echo; ok \"Dry run of the docker", "elif false; then\n  echo; ok \"Dry run of the docker"),
        ("    $DRYRUN || NEW_LOGIN=yes", "    NEW_LOGIN=yes"),
    ]:
        assert inst.count(a) == 1, "perturbation anchor missing — this run would FALSE-PASS: %r" % a[:60]
        inst = inst.replace(a, b, 1)
    open(INST_SH, "w", encoding="utf-8").write(inst)

NODE_ENV = """# generated by install-docker.sh — profile: node
PANEL_PASSWORD=unused-on-node-only
PANEL_DOMAIN=localhost
PANEL_URL=https://127.0.0.1:9
NODE_TOKEN=stored-token-0123456789
NODE_ENDPOINT=192.168.77.4
NODE_NET=host
TURN_MANAGE=panel
TLS_VERIFY=yes
"""


def dry(label, args, stored=None, env_extra=None):
    inst_dir = os.path.join(T, "inst-" + label)
    if stored is not None:
        os.makedirs(inst_dir); open(os.path.join(inst_dir, ".env"), "w").write(stored)
    env = dict(os.environ, SWG_DOCKER_DIR=inst_dir)
    for k in ("NODE_NET", "TLS", "ROLE", "PANEL_DOMAIN"):
        env.pop(k, None)
    env.update(env_extra or {})
    r = subprocess.run(["bash", "install-docker.sh", *args, "--dry-run"], cwd=SRC, env=env, stdin=subprocess.DEVNULL,
                       capture_output=True, text=True, timeout=300, start_new_session=True)
    return r.returncode, r.stdout + r.stderr


def no_raw_tty(out):
    return not re.search(r"/dev/tty|No such device or address", out)


print("[1] fresh master, no terminal")
rc, out = dry("fresh", ["host", "-role", "master", "-pass", "dry-run-pass-123", "-domain", "192.0.2.10", "-tls", "selfsigned"])
check("the dry run completed", rc == 0 and "DRY RUN done" in out, (rc, out[-400:]))
check("the Networking-mode menu was reached (the case measured)", "Networking mode" in out)
check("⚠️ no raw /dev/tty error", no_raw_tty(out), re.findall(r".*(?:/dev/tty|No such device).*", out)[:3])
check("each default it took is named", out.count("(no terminal — default taken)") >= 2, out.count("(no terminal — default taken)"))

print("\n[2] node re-install, no terminal")
rc, out2 = dry("node", ["node"], stored=NODE_ENV)
check("the dry run completed", rc == 0 and "DRY RUN done" in out2, (rc, out2[-400:]))
check("no 'Press Enter' without a terminal", "Press" not in out2, re.findall(r".*Press.*", out2))
check("no raw /dev/tty error", no_raw_tty(out2), re.findall(r".*(?:/dev/tty|No such device).*", out2)[:3])

print("\n[3] a dry run says what it did — and only that")
both = out + out2
check("⚠️ no 'COMPLETE' banner", "COMPLETE" not in both, re.findall(r".*COMPLETE.*", both))
check("⚠️ no 'new login — save the password' (nothing was applied)", "new login" not in both and "save the password" not in both)
check("the banner no longer claims 'no Docker commands run'", "no Docker commands run" not in both)
check("it says nothing was installed or changed", "nothing was installed or changed" in both)

shutil.rmtree(T, ignore_errors=True)
print("\n%s — %d failed" % ("RED" if FAILS else "GREEN", len(FAILS)))
if PERTURB:
    print("(--perturb expects RED above)")
sys.exit(1 if FAILS else 0)
