#!/usr/bin/env python3
"""Self-test: a docker RE-INSTALL keeps the .env keys it has no new value for — the image pin above all.

Measured in the 1.8.8-beta qualification (guests q3/q4): re-running install-docker.sh WITHOUT exporting
SWG_IMAGE_TAG again moved panel and node from sha-6bd6d8c to `latest` (= 1.8.7-beta) — a silent downgrade — and the
operator's SWG_LATEST_URL (the pre-release update channel .env.example tells them to add) vanished. install-docker.sh
rewrites .env WHOLE from a heredoc, so every key it does not itself write was deleted, and it wrote SWG_IMAGE_TAG only
when the variable was exported. Seen on the same box: `CONSOLE_PORT=8445   # …   # …` — the import read each value
with its inline comment, so every re-install appended one more copy of it; and PANEL_LOCAL_PORT, which the panel
itself moves (swg-netctl-docker set-local-port), was never imported, so a re-install put it back to 8088.

  [1] non---build re-install: the stored SWG_IMAGE_TAG pin is kept (exactly once)
  [2] SWG_LATEST_URL, SWG_TURN_MIRROR, PULL_POLICY and an operator's own key are kept, byte for byte
  [3] no key is written twice; the kept block's header does not pile up across re-installs
  [4] an inline comment is not re-imported as part of the value (one `#` on the CONSOLE_PORT line)
  [5] PANEL_LOCAL_PORT is kept — and the co-located node's loopback URL follows it
  [6] the tag a --build stamped on its own images is NOT carried into an image-pulling re-install
  [7] an exported SWG_IMAGE_TAG still wins over the stored one

Real `install-docker.sh --dry-run` runs in a copy of the tree against a stored .env in SWG_DOCKER_DIR.

Run: python3 tests/docker_reinstall_keeps_env_keys_selftest.py      (0 = pass)
     --perturb   re-plants the shipped rewrite (no stored-tag branch, no carry-forward, raw value import, no
                 PANEL_LOCAL_PORT import) → RED
"""
import os, re, shutil, subprocess, sys, tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PERTURB = "--perturb" in sys.argv
FAILS = []


def check(name, cond, detail=""):
    print(("  PASS " if cond else "  FAIL ") + name + (("  — %s" % (detail,)) if detail and not cond else ""))
    if not cond:
        FAILS.append(name)


T = tempfile.mkdtemp(prefix="dockerenvkeys-")
SRC = os.path.join(T, "src")
shutil.copytree(ROOT, SRC, ignore=shutil.ignore_patterns(".git", "dryrun", "node_modules", "*.png", "scratchpad", "docs",
                                                         ".campaign", "__pycache__", "forks", "screenshots", ".claude"))
INST_SH = os.path.join(SRC, "install-docker.sh")
inst = open(INST_SH, encoding="utf-8").read()
if PERTURB:
    m = re.search(r"\nelif _prev_tag=.*?\n  case \"\$_prev_tag\" in .*?\n", inst)
    assert m, "perturbation anchor missing (stored-tag branch) — this run would FALSE-PASS"
    inst = inst[:m.start()] + "\n" + inst[m.end():]
    for a, b in [
        ('if [ -n "$_OLD_ENV" ]; then', "if false; then"),
        ('''    _v="$(_env_val "$_k" "$INSTALL_DIR/.env")"''',
         '''    _v="$(sed -n "s/^${_k}=//p" "$INSTALL_DIR/.env" 2>/dev/null | head -1)"; _v="${_v%\\"}"; _v="${_v#\\"}"'''),
        ("            PANEL_LOCAL_PORT SUB_PORT SUB_DOMAIN PANEL_BIND", "            SUB_PORT SUB_DOMAIN PANEL_BIND"),
    ]:
        assert inst.count(a) == 1, "perturbation anchor missing — this run would FALSE-PASS: %r" % a[:60]
        inst = inst.replace(a, b, 1)
    open(INST_SH, "w", encoding="utf-8").write(inst)

BASE = """# generated by install-docker.sh — profile: master
PANEL_PASSWORD=storedpass123
PANEL_USER=admin899
PANEL_DOMAIN=10.0.2.15
TLS=selfsigned
PANEL_PORT=2087
PANEL_LOCAL_PORT=8099   # dedicated STABLE plain-HTTP loopback port
CONSOLE_PORT=8445     # the operator console's own port     # the operator console's own port
SUB_PORT=8444
PANEL_URL=http://127.0.0.1:8099
NODE_TOKEN=stored-token-0123456789
NODE_ENDPOINT=192.168.77.3
NODE_NET=host
TURN_MANAGE=panel
TLS_VERIFY=no
"""
EXTRA = """SWG_LATEST_URL=https://raw.githubusercontent.com/SanityProtocol/swg-panel/dev/VERSION
SWG_TURN_MIRROR=https://mirror.example/turn   # my mirror
PULL_POLICY=always
MY_OWN_KNOB=42
"""


def dry(label, stored, args=(), env_extra=None):
    inst_dir = os.path.join(T, "inst-" + label); os.makedirs(inst_dir)
    open(os.path.join(inst_dir, ".env"), "w").write(stored)
    env = dict(os.environ, SWG_DOCKER_DIR=inst_dir)
    for k in ("SWG_IMAGE_TAG", "SWG_LATEST_URL", "PANEL_LOCAL_PORT", "TLS"):
        env.pop(k, None)
    env.update(env_extra or {})
    r = subprocess.run(["bash", "install-docker.sh", "host", "-role", "master", *args, "--dry-run"], cwd=SRC, env=env,
                       stdin=subprocess.DEVNULL, capture_output=True, text=True, timeout=300, start_new_session=True)
    rendered = os.path.join(SRC, "dryrun" + inst_dir, ".env")
    return r.returncode, r.stdout + r.stderr, (open(rendered).read() if os.path.exists(rendered) else "")


def keys(txt):
    return [m.group(1) for m in re.finditer(r"^([A-Za-z_][A-Za-z0-9_]*)=", txt, re.M)]


def val(txt, k):
    m = re.search(r"^%s=(.*)$" % k, txt, re.M)
    return re.sub(r"\s+#.*$", "", m.group(1)).strip() if m else None


rc, out, env1 = dry("pin", BASE + EXTRA + "SWG_IMAGE_TAG=sha-6bd6d8c\n")
print("[1] the stored image pin is kept")
check("the dry run completed", rc == 0 and "DRY RUN done" in out, (rc, out[-400:]))
check("⚠️ SWG_IMAGE_TAG=sha-6bd6d8c", val(env1, "SWG_IMAGE_TAG") == "sha-6bd6d8c", val(env1, "SWG_IMAGE_TAG"))

print("\n[2] operator keys the installer does not write are kept, byte for byte")
for line in EXTRA.strip().splitlines():
    check("kept: " + line.split("=")[0], re.search("^" + re.escape(line) + "$", env1, re.M) is not None)

print("\n[3] nothing twice, and the kept-block header does not pile up")
dup = sorted({k for k in keys(env1) if keys(env1).count(k) > 1})
check("no key appears twice", not dup, dup)
rc, out, env2 = dry("again", env1)                  # a second re-install over the first one's output
check("a second re-install: still no duplicates", not sorted({k for k in keys(env2) if keys(env2).count(k) > 1}))
check("…one 'kept from the previous .env' header, not two", env2.count("kept from the previous .env") == 1, env2.count("kept from the previous .env"))
check("…and the pin + operator keys survive it too",
      val(env2, "SWG_IMAGE_TAG") == "sha-6bd6d8c" and val(env2, "MY_OWN_KNOB") == "42", (val(env2, "SWG_IMAGE_TAG"), val(env2, "MY_OWN_KNOB")))

print("\n[4] an inline comment is not re-imported as the value")
cl = next((l for l in env1.splitlines() if l.startswith("CONSOLE_PORT=")), "")
check("CONSOLE_PORT=8445 with exactly one comment", val(env1, "CONSOLE_PORT") == "8445" and cl.count("#") == 1, cl)

print("\n[5] PANEL_LOCAL_PORT is kept, and the local node dials it")
check("PANEL_LOCAL_PORT=8099", val(env1, "PANEL_LOCAL_PORT") == "8099", val(env1, "PANEL_LOCAL_PORT"))
check("PANEL_URL=http://127.0.0.1:8099", val(env1, "PANEL_URL") == "http://127.0.0.1:8099", val(env1, "PANEL_URL"))

print("\n[6] a --build's own tag does not come back on an image-pulling re-install")
rc, out, env3 = dry("buildtag", BASE + "SWG_IMAGE_TAG=local   # built on this box from source — not a published GHCR tag\n")
check("the dry run completed", rc == 0 and "DRY RUN done" in out, (rc, out[-400:]))
check("no SWG_IMAGE_TAG line (pulls the published image)", "SWG_IMAGE_TAG" not in keys(env3), val(env3, "SWG_IMAGE_TAG"))

print("\n[7] an exported SWG_IMAGE_TAG wins")
rc, out, env4 = dry("export", BASE + "SWG_IMAGE_TAG=sha-6bd6d8c\n", env_extra={"SWG_IMAGE_TAG": "sha-3a550ee"})
check("SWG_IMAGE_TAG=sha-3a550ee, once", val(env4, "SWG_IMAGE_TAG") == "sha-3a550ee" and keys(env4).count("SWG_IMAGE_TAG") == 1,
      (val(env4, "SWG_IMAGE_TAG"), keys(env4).count("SWG_IMAGE_TAG")))

shutil.rmtree(T, ignore_errors=True)
print("\n%s — %d failed" % ("RED" if FAILS else "GREEN", len(FAILS)))
if PERTURB:
    print("(--perturb expects RED above)")
sys.exit(1 if FAILS else 0)
