#!/usr/bin/env python3
"""Self-test: on a docker RE-INSTALL, a value the operator gives THIS run wins over the one stored in .env.

Measured in the 1.8.8-beta qualification (KVM guests q3/q6): a docker master installed at 192.168.77.6, re-run with
`-domain 10.0.2.15`, kept serving 192.168.77.6 — and the other way round on q3, `-domain 192.168.77.3` came back as
https://10.0.2.15:2087 with a NEW certificate issued for 10.0.2.15. install-docker.sh snapshots which settings the
caller gave (`_GIVEN_*`) BEFORE the flags are parsed, so every flag looked "not given" and the .env import put the
stored value back over it. bootstrap.sh's `-endpoint` arrives as ENDPOINT_IP, which the snapshot never looked at.
The same run printed a TLS menu announcing "[r]euse (default) … it already covers 10.0.2.15" over a TLS that had
been GIVEN (TLS=selfsigned) and was then applied without a question — a menu describing a choice nobody was offered.

  [1] master re-install: `-domain` replaces the stored PANEL_DOMAIN (the .env and the URL it would serve)
  [2] …and `-port` / `-user` / `-base` replace theirs
  [3] node re-install: bootstrap's ENDPOINT_IP, and the `-endpoint` flag, replace the stored NODE_ENDPOINT
  [4] nothing given → every stored value is kept (the import still does its job)
  [5] a GIVEN TLS prints no menu (it says it was given); an un-given one still offers "reuse" when the cert covers the host

Every scenario is a real `install-docker.sh --dry-run` in a copy of the tree, with a stored .env in SWG_DOCKER_DIR,
detached from any terminal (as `setsid … </dev/null`).

Run: python3 tests/docker_reinstall_given_wins_selftest.py      (0 = pass)
     --perturb   re-plants the shipped behaviour (flags not recorded as given, ENDPOINT_IP not snapshotted, the menu
                 printed over a given TLS) → RED
"""
import os, re, shutil, subprocess, sys, tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PERTURB = "--perturb" in sys.argv
FAILS = []


def check(name, cond, detail=""):
    print(("  PASS " if cond else "  FAIL ") + name + (("  — %s" % (detail,)) if detail and not cond else ""))
    if not cond:
        FAILS.append(name)


T = tempfile.mkdtemp(prefix="dockergiven-")
SRC = os.path.join(T, "src")
shutil.copytree(ROOT, SRC, ignore=shutil.ignore_patterns(".git", "dryrun", "node_modules", "*.png", "scratchpad", "docs",
                                                         ".campaign", "__pycache__", "forks", "screenshots", ".claude"))
INST_SH = os.path.join(SRC, "install-docker.sh")
inst = open(INST_SH, encoding="utf-8").read()
if PERTURB:
    for a, b in [
        # the flag parser sets the value but does not record it as given
        ("""_flag(){ printf -v "$1" '%s' "$2"; printf -v "_GIVEN_$1" '%s' "$2"; }""", """_flag(){ printf -v "$1" '%s' "$2"; }"""),
        # bootstrap's ENDPOINT_IP never reaches the snapshot
        ('''_GIVEN_NODE_ENDPOINT="${NODE_ENDPOINT:-${ENDPOINT_IP:-}}"''', ""),
        # the TLS menu printed whatever the caller gave
        ('''    if [ -n "${TLS:-}" ] && _in "$TLS" "$_opts"; then''', '''    if false; then'''),
    ]:
        assert inst.count(a) == 1, "perturbation anchor missing — this run would FALSE-PASS: %r" % a[:60]
        inst = inst.replace(a, b, 1)
    open(INST_SH, "w", encoding="utf-8").write(inst)

STORED_MASTER = """# generated by install-docker.sh — profile: master
PANEL_PASSWORD=storedpass123
PANEL_USER=admin899
PANEL_DOMAIN=10.0.2.15
PANEL_BASE=
TLS=selfsigned
PANEL_PORT=2087
SUB_PORT=8444
PANEL_URL=http://127.0.0.1:8088
NODE_TOKEN=stored-token-0123456789
NODE_ENDPOINT=192.168.77.3
NODE_NET=host
TURN_MANAGE=panel
TLS_VERIFY=no
"""
STORED_NODE = """# generated by install-docker.sh — profile: node
PANEL_PASSWORD=unused-on-node-only
PANEL_DOMAIN=localhost
PANEL_URL=https://127.0.0.1:9
NODE_TOKEN=stored-token-0123456789
NODE_ENDPOINT=192.168.77.4
NODE_NET=host
TURN_MANAGE=panel
TLS_VERIFY=yes
"""


def dry(label, stored, args, env_extra=None, cert_for=None):
    inst_dir = os.path.join(T, "inst-" + label)
    os.makedirs(inst_dir)
    open(os.path.join(inst_dir, ".env"), "w").write(stored)
    if cert_for:
        tls = os.path.join(inst_dir, "data", "etc", "tls"); os.makedirs(tls)
        subprocess.run(["openssl", "req", "-x509", "-newkey", "rsa:2048", "-nodes", "-days", "30", "-subj", "/CN=%s" % cert_for,
                        "-addext", "subjectAltName=IP:%s" % cert_for, "-keyout", os.path.join(tls, "key.pem"),
                        "-out", os.path.join(tls, "fullchain.pem")], check=True, capture_output=True)
    env = dict(os.environ, SWG_DOCKER_DIR=inst_dir)
    for k in ("TLS", "PANEL_DOMAIN", "ENDPOINT_IP", "NODE_ENDPOINT", "SWG_IMAGE_TAG", "TLS_VERIFY", "TLS_FINGERPRINT"):
        env.pop(k, None)
    env.update(env_extra or {})
    r = subprocess.run(["bash", "install-docker.sh", *args, "--dry-run"], cwd=SRC, env=env, stdin=subprocess.DEVNULL,
                       capture_output=True, text=True, timeout=300, start_new_session=True)
    out = r.stdout + r.stderr
    rendered = os.path.join(SRC, "dryrun" + inst_dir, ".env")
    envtxt = open(rendered).read() if os.path.exists(rendered) else ""
    vals = {}
    for ln in envtxt.splitlines():
        m = re.match(r"^([A-Za-z_][A-Za-z0-9_]*)=(.*)$", ln)
        if m and m.group(1) not in vals:
            vals[m.group(1)] = re.sub(r"\s+#.*$", "", m.group(2)).strip()
    return r.returncode, out, vals


print("[1] master re-install: -domain replaces the stored PANEL_DOMAIN")
rc, out, v = dry("domain", STORED_MASTER, ["host", "-role", "master", "-domain", "192.168.77.3"])
check("the dry run completed", rc == 0 and "DRY RUN done" in out, (rc, out[-400:]))
check("⚠️ PANEL_DOMAIN is the flag's 192.168.77.3, not the stored 10.0.2.15", v.get("PANEL_DOMAIN") == "192.168.77.3", v.get("PANEL_DOMAIN"))
check("the URL it would serve names 192.168.77.3 (stored port kept)", "https://192.168.77.3:2087/" in out, out[-600:])

print("\n[2] master re-install: -port / -user / -base replace theirs")
rc, out, v = dry("portuserbase", STORED_MASTER, ["host", "-role", "master", "-port", "8443", "-user", "alice", "-base", "swg"])
check("the dry run completed", rc == 0 and "DRY RUN done" in out, (rc, out[-400:]))
check("PANEL_PORT is the flag's 8443", v.get("PANEL_PORT") == "8443", v.get("PANEL_PORT"))
check("PANEL_USER is the flag's alice", v.get("PANEL_USER") == "alice", v.get("PANEL_USER"))
check("PANEL_BASE is the flag's /swg", v.get("PANEL_BASE") == "/swg", v.get("PANEL_BASE"))
check("PANEL_DOMAIN (not given) is still the stored one", v.get("PANEL_DOMAIN") == "10.0.2.15", v.get("PANEL_DOMAIN"))

print("\n[3] node re-install: bootstrap's ENDPOINT_IP and the -endpoint flag replace the stored NODE_ENDPOINT")
rc, out, v = dry("epenv", STORED_NODE, ["node"], {"ENDPOINT_IP": "198.51.100.9"})
check("the dry run completed", rc == 0 and "DRY RUN done" in out, (rc, out[-400:]))
check("⚠️ ENDPOINT_IP=198.51.100.9 (bootstrap -endpoint) wins", v.get("NODE_ENDPOINT") == "198.51.100.9", v.get("NODE_ENDPOINT"))
rc, out, v = dry("epflag", STORED_NODE, ["node", "-endpoint", "198.51.100.10"])
check("the -endpoint flag wins", rc == 0 and v.get("NODE_ENDPOINT") == "198.51.100.10", (rc, v.get("NODE_ENDPOINT")))

print("\n[4] nothing given → the stored values are kept")
rc, out, v = dry("none", STORED_MASTER, ["host", "-role", "master"])
check("the dry run completed", rc == 0 and "DRY RUN done" in out, (rc, out[-400:]))
check("PANEL_DOMAIN / PANEL_PORT / PANEL_USER stay stored",
      (v.get("PANEL_DOMAIN"), v.get("PANEL_PORT"), v.get("PANEL_USER")) == ("10.0.2.15", "2087", "admin899"),
      (v.get("PANEL_DOMAIN"), v.get("PANEL_PORT"), v.get("PANEL_USER")))
rc, out, v = dry("nonenode", STORED_NODE, ["node"])
check("NODE_ENDPOINT stays stored on a node re-install", v.get("NODE_ENDPOINT") == "192.168.77.4", v.get("NODE_ENDPOINT"))

print("\n[5] a GIVEN TLS prints no menu; an un-given one still offers reuse")
rc, out, v = dry("tlsgiven", STORED_MASTER, ["host", "-role", "master"], {"TLS": "selfsigned"}, cert_for="10.0.2.15")
check("the dry run completed", rc == 0 and "DRY RUN done" in out, (rc, out[-400:]))
check("⚠️ no \"reuse (default)\" menu over a given TLS", "euse (default)" not in out, re.findall(r".*euse.*", out))
check("…it says the TLS was given", "(given — not asked)" in out, out[-800:])
rc, out, v = dry("tlsask", STORED_MASTER, ["host", "-role", "master"], cert_for="10.0.2.15")
check("un-given TLS + a covering cert: reuse is offered as the default", "euse (default)" in out, out[-800:])

shutil.rmtree(T, ignore_errors=True)
print("\n%s — %d failed" % ("RED" if FAILS else "GREEN", len(FAILS)))
if PERTURB:
    print("(--perturb expects RED above)")
sys.exit(1 if FAILS else 0)
