#!/usr/bin/env python3
"""Self-test — an update of a Docker NODE-only box writes no panel files and seeds no panel settings.

update.sh ran two panel heals for every Docker profile. On a node-only box the first update therefore created the four
empty panel files swg-sub masks (data/etc/auth 0 bytes, mode 644, among them), and the next update found ".env and
data/lib" there — ensure_access_seed's whole Docker test — and wrote a panel URL of https://localhost into a panel that
does not exist, printing a bare "public URL, TLS type" line (1.8.8 qualification, round 4; since 1.4.0). install-docker.sh
said "update.sh already guards its call"; it did not.

  [1] the update's Docker heals on a NODE-only stack: no panel file is created, no settings are written
  [2] …on a master and a panel-only stack: both heals run, as before
  [3] ensure_access_seed on its own: a node-only stack is not a panel, even with .env and data/lib on disk

update.sh's block and ensure_access_seed are lifted as shipped; lib/common.sh's ensure_docker_mask_files is the real one.

Run: python3 tests/node_only_panel_heal_selftest.py      (0 = pass)
     --plant <mask|seed>   plant one old behaviour → RED (exit 0 when caught);  --perturb plants both
"""
import json, os, re, subprocess, sys, tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, ".."))
UP = open(os.path.join(ROOT, "update.sh"), encoding="utf-8").read()
C = open(os.path.join(ROOT, "lib", "common.sh"), encoding="utf-8").read()
ALL = ("mask", "seed")
PLANTS = set(ALL) if "--perturb" in sys.argv else ({sys.argv[sys.argv.index("--plant") + 1]} if "--plant" in sys.argv else set())

FAILS = []
def check(name, ok, detail=""):
    print(("  PASS " if ok else "  FAIL ") + name + (("  — " + str(detail)[:600]) if detail and not ok else ""))
    if not ok:
        FAILS.append(name)

def plant(src, a, b):
    assert src.count(a) == 1, "perturbation anchor missing — would FALSE-PASS: " + a[:90]
    return src.replace(a, b)

BA = "  # ⚠️ PANEL-BEARING PROFILES ONLY, both."
if "mask" in PLANTS:     # the shipped docker branch: both heals for every profile
    a = UP.index(BA); b = UP.index("  ;; esac\n", a) + len("  ;; esac\n")
    UP = UP[:a] + ("  ensure_access_seed\n  $DRYRUN || ensure_docker_mask_files \"$DOCKER_DIR\"\n") + UP[b:]
if "seed" in PLANTS:     # the shipped docker test: ".env and data/lib exist"
    UP = plant(UP, ' && case "$(docker_profile 2>/dev/null | tail -n1)" in host|master|host-node) true;; *) false;; esac; then\n', "; then\n")

def fn(src, name):
    m = re.search(r"^%s\(\)\{" % re.escape(name), src, re.M)
    assert m, "cannot extract " + name
    lines = src[m.start():].split("\n")
    for k, l in enumerate(lines):
        if l.split("  #")[0].rstrip().endswith("}"):
            text = "\n".join(lines[:k + 1]) + "\n"
            if subprocess.run(["bash", "-n"], input=text, capture_output=True, text=True).returncode == 0:
                return text
    raise AssertionError("unterminated " + name)

a = UP.index(BA) if "mask" not in PLANTS else UP.index("  ensure_access_seed\n  $DRYRUN || ensure_docker_mask_files")
b = UP.index("  ;; esac\n", a) + len("  ;; esac\n") if "mask" not in PLANTS else UP.index("\n", UP.index("ensure_docker_mask_files", a)) + 1
HEALS = UP[a:b]
SEED = fn(UP, "ensure_access_seed")
MASK = fn(C, "ensure_docker_mask_files")
PRE = ('set -uo pipefail\nDRYRUN=false\nsub(){ echo "SUB $*"; }; ok(){ echo "OK $*"; }; info(){ echo "INFO $*"; }; note(){ :; }\n'
       'have(){ command -v "$1" >/dev/null; }\n')

def box(profile):
    d = tempfile.mkdtemp(prefix="nophe-")
    os.makedirs(os.path.join(d, "data", "lib")); os.makedirs(os.path.join(d, "data", "node"))
    open(os.path.join(d, ".env"), "w").write("# generated by install-docker.sh — profile: %s\nPANEL_DOMAIN=localhost\nPANEL_PORT=\nTLS=selfsigned\n" % profile)
    return d
def files(d):
    return sorted(os.path.relpath(os.path.join(r, f), d) for r, _, fs in os.walk(d) for f in fs)

print("[1]–[2] the update's Docker heals")
for profile in ("node", "master", "host"):
    d = box(profile)
    out = subprocess.run(["bash", "-c", PRE + 'DOCKER_DIR=%s; PANEL_DIR=/nonexistent; prof=%s\ndocker_profile(){ echo %s; }\n%s%s%sf(){\n%s}\nf\n' % (
        d, profile, profile, SEED, MASK, "", HEALS)], capture_output=True, text=True)
    got = files(d)
    if profile == "node":
        check("[1] a node-only stack: no panel file appears (auth, panel-settings, vault, escrow)",
              got == [".env"], (got, out.stdout + out.stderr))
    else:
        check("[2] a %s stack: the four placeholders and the seeded settings, as before" % profile,
              all(x in got for x in ("data/etc/auth", "data/lib/panel-settings.json", "data/lib/subs/vault.json", "data/lib/subs/escrow.json")),
              (got, out.stdout + out.stderr))
        ps = json.load(open(os.path.join(d, "data/lib/panel-settings.json"))) if "data/lib/panel-settings.json" in got else {}
        check("[2] …with the panel's address seeded from .env (%s)" % profile, (ps.get("access") or {}).get("panel", {}).get("url") == "https://localhost", ps)

print("\n[3] ensure_access_seed on its own")
d = box("node"); os.makedirs(os.path.join(d, "data", "lib", "subs")); open(os.path.join(d, "data", "lib", "panel-settings.json"), "w").write("")
out = subprocess.run(["bash", "-c", PRE + 'DOCKER_DIR=%s; PANEL_DIR=/nonexistent\ndocker_profile(){ echo node; }\n%sensure_access_seed\n' % (d, SEED)],
                     capture_output=True, text=True)
check("[3] a node-only stack with a placeholder panel-settings.json: nothing is written into it",
      open(os.path.join(d, "data", "lib", "panel-settings.json")).read() == "" and "public URL" not in out.stdout, out.stdout + out.stderr)

print()
if PLANTS:
    print("PERTURBED (%s): %s" % (",".join(sorted(PLANTS)), "RED as expected (%d failing)" % len(FAILS) if FAILS else "STILL GREEN — the gate does not see the defect"))
    sys.exit(0 if FAILS else 2)
print("FAILED: " + ", ".join(FAILS) if FAILS else "ALL PASS")
sys.exit(1 if FAILS else 0)
